# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getmagiceye <- function(x, y, shift) {
    .Call('magiceyer_getmagiceye', PACKAGE = 'magiceyer', x, y, shift)
}

